### ISSUE TITLE
Multiple attempts to reload as key is updated

### ISSUE THREAD

**Issue by scottastanley** [scottastanley/reload_sslkey_jetty_module#1]
When the pkcs12 key is being regenerated, the change in the file is being noticed multiple times as the new file is written and the reload is being triggered multiple times.  The first few attempts to reload are failing since the key is not fully written.

The following log was triggered by a single reconversion of the key.  However, when I touch the new file after it has been generated it is loaded successfully with no errors.

```
2018-12-12 05:03:41.760:INFO:cbr.FileWatcher:Thread-19: File modified:  /opt/fermenation/data/ssl_certs/fermenation_com.pkcs12
2018-12-12 05:03:41.760:INFO:cbr.ReloadSslKeysModule:Thread-19: Reloading keys in SslContextFactory
2018-12-12 05:03:41.760:INFO:cbr.ReloadSslKeysModule:Thread-19: Failed reloading SslCOntextFactory
java.io.IOException: Short read of DER length
	at sun.security.util.DerInputStream.getLength(DerInputStream.java:582)
	at sun.security.util.DerValue.init(DerValue.java:391)
	at sun.security.util.DerValue.<init>(DerValue.java:332)
	at sun.security.util.DerValue.<init>(DerValue.java:345)
	at sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:1938)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at org.eclipse.jetty.util.security.CertificateUtils.getKeyStore(CertificateUtils.java:54)
	at org.eclipse.jetty.util.ssl.SslContextFactory.loadKeyStore(SslContextFactory.java:1137)
	at org.eclipse.jetty.util.ssl.SslContextFactory.load(SslContextFactory.java:313)
	at org.eclipse.jetty.util.ssl.SslContextFactory.reload(SslContextFactory.java:1750)
	at com.bb.reload_ssl_keys.ReloadSslKeysModule.lambda$doStart$1(ReloadSslKeysModule.java:33)
	at com.bb.reload_ssl_keys.FileWatcher.lambda$new$2(FileWatcher.java:60)
	at java.lang.Thread.run(Thread.java:748)
2018-12-12 05:03:41.766:INFO:cbr.FileWatcher:Thread-19: File modified:  /opt/fermenation/data/ssl_certs/fermenation_com.pkcs12
2018-12-12 05:03:41.766:INFO:cbr.ReloadSslKeysModule:Thread-19: Reloading keys in SslContextFactory
2018-12-12 05:03:41.766:INFO:cbr.ReloadSslKeysModule:Thread-19: Failed reloading SslCOntextFactory
java.io.EOFException: Detect premature EOF
	at sun.misc.IOUtils.readFully(IOUtils.java:68)
	at sun.security.util.DerValue.init(DerValue.java:412)
	at sun.security.util.DerValue.<init>(DerValue.java:332)
	at sun.security.util.DerValue.<init>(DerValue.java:345)
	at sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:1938)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at org.eclipse.jetty.util.security.CertificateUtils.getKeyStore(CertificateUtils.java:54)
	at org.eclipse.jetty.util.ssl.SslContextFactory.loadKeyStore(SslContextFactory.java:1137)
	at org.eclipse.jetty.util.ssl.SslContextFactory.load(SslContextFactory.java:313)
	at org.eclipse.jetty.util.ssl.SslContextFactory.reload(SslContextFactory.java:1750)
	at com.bb.reload_ssl_keys.ReloadSslKeysModule.lambda$doStart$1(ReloadSslKeysModule.java:33)
	at com.bb.reload_ssl_keys.FileWatcher.lambda$new$2(FileWatcher.java:60)
	at java.lang.Thread.run(Thread.java:748)
2018-12-12 05:03:41.769:INFO:cbr.FileWatcher:Thread-19: File modified:  /opt/fermenation/data/ssl_certs/fermenation_com.pkcs12
2018-12-12 05:03:41.769:INFO:cbr.ReloadSslKeysModule:Thread-19: Reloading keys in SslContextFactory
2018-12-12 05:03:41.777:INFO:oejus.SslContextFactory:Thread-19: x509=X509@56054665(fermenation,h=[fermenation.com],w=[]) for SslContextFactory@386aa805[provider=null,keyStore=file:///opt/fermenation/data/ssl_certs/fermenation_com.pkcs12,trustStore=file:///opt/fermenation/data/ssl_certs/fermenation_com.pkcs12]
2018-12-12 05:03:41.782:INFO:cbr.FileWatcher:Thread-19: File modified:  /opt/fermenation/data/ssl_certs/fermenation_com.pkcs12
2018-12-12 05:03:41.783:INFO:cbr.ReloadSslKeysModule:Thread-19: Reloading keys in SslContextFactory
2018-12-12 05:03:41.793:INFO:oejus.SslContextFactory:Thread-19: x509=X509@5ebc175b(fermenation,h=[fermenation.com],w=[]) for SslContextFactory@386aa805[provider=null,keyStore=file:///opt/fermenation/data/ssl_certs/fermenation_com.pkcs12,trustStore=file:///opt/fermenation/data/ssl_certs/fermenation_com.pkcs12]
```

**Comment by scottastanley** [comment]
In order to eliminate the spurious errors, I need to implement some form of wait logic to insure the file is completely written before triggering the reload.  Some form of debounce logic.
